name: Test build

on:
  push:
  pull_request:

jobs:
  build-ppx:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.2

      - name: Install PPX dependencies
        working-directory: packages/ppx
        run: opam install . --deps-only -y

      - name: Build PPX
        working-directory: packages/ppx
        run: opam exec -- dune build

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Build demo
        working-directory: packages/demo
        run: |
          npm install
          npm run build
